import { usePathname } from "next/navigation"; // 👈 agregá esto
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientProviders from "@/components/ClientProviders";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Turnos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); // 👈 detectamos la ruta

  const isLoginPage = pathname === "/login"; // ✅ chequeamos si estamos en login

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProviders>
          <Header />
          <main className={`${!isLoginPage ? "pt-10" : ""}`}>
            {children}
          </main>
        </ClientProviders>
      </body>
    </html>
  );
}
